export const SKILLS_LIST = [
    'Java',
    'Spring',
    'Kotlin',
    'Maven',
    'NPM',
    'Conlfuence & Jira',
    'CSS3',
    'Angular',
    'TypeScript',
    'Jenkins',
    'Kibana',
    'Adobe Analytics',
    'Openshift',
    'GitLab',
    'GitHub',
    'Firebase',
    'Gradle',
    'XML',
    'PostgreSQL',
    'CI/CD',
    'REST API',
    'NodeJS',
    'Dynatrace',
    'TDD & BDD'
];
